[workspace]
members = ["./", "compio-core", "compio-threadpool", "compio-local", "compio-net", "compio-ipc"]

[profile.bench]
debug = 1

[package]
name = "compio"
version = "0.1.0"
edition = "2018"

[dependencies]
compio-core = { version = "0.1.0", path = "./compio-core" }
