cargo-features = ["rename-dependency"]

[package]
name = "compio-threadpool"
version = "0.1.0"
edition = "2018"

[dependencies]
compio-core = { version = "0.1.0", path = "../compio-core" }

num_cpus = "1.8"
futures_core = { package = "futures-core-preview", version = "=0.3.0-alpha.9" }