[package]
name = "compio-local"
version = "0.1.0"
edition = "2018"

[dependencies]
compio-core = { version = "0.1.0", path = "../compio-core" }

pin-utils = "=0.1.0-alpha.4"
scoped-tls = "0.1.2"
futures-core = "0.3.4"
futures-util = "0.3.4"
futures-task = "0.3.4"