name: ci
on: [push]

env:
  RUSTFLAGS: -Dwarnings
  CI_RUST_VER: 1.47.0

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
            # TODO: not all io_uring features are supported on 20.04
            - ubuntu-20.04
            - ubuntu-16.04
            - windows-2019
            - macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup default $CI_RUST_VER
      - name: Check uname
        run: uname -r
      - name: Install cargo hack
        run: cargo install cargo-hack
      - name: Run tests
        # TODO: figure out why io_uring can't be used on GitHub runners
        run: cargo hack --color=always test --workspace --no-default-features

  check-rustfmt:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup default $CI_RUST_VER
      - name: Download rustfmt
        run: rustup component add rustfmt
      - name: Run rustfmt
        run: cargo fmt --color=always
